### ISSUE TITLE
"0 reads mapped" in sample where CellRanger maps 66M reads / 9915 cells

### ISSUE THREAD

**Issue by wmacnair** [COMBINE-lab/piscem#15]
Hi @rob-p and team

We have a very strange issue with `piscem`... (Called by `simpleaf` but `piscem` seemed like the natural place for this issue.)

The sample mapped fine with `CellRanger`, as noted in the title, but `piscem` mapped 0 reads. 

Here is the contents of the _map_info.json_ file:
```json
{
    "cmdline": "sc_ref_mapper -i /projects/site/pred/neurogenomics/resources/scprocess_data/data/alevin_fry_home/human_2020-A_splici/index/piscem_idx -g chromium_v3 -1 /projects/site/pred/neurogenomics/users/macnairw/Macnair_2022/data/fastqs/zero_mapping_POOL1_S3_L001_R1_001.fastq.gz,/projects/site/pred/neurogenomics/users/macnairw/Macnair_2022/data/fastqs/zero_mapping_POOL1_S3_L002_R1_001.fastq.gz -2 /projects/site/pred/neurogenomics/users/macnairw/Macnair_2022/data/fastqs/zero_mapping_POOL1_S3_L001_R2_001.fastq.gz,/projects/site/pred/neurogenomics/users/macnairw/Macnair_2022/data/fastqs/zero_mapping_POOL1_S3_L002_R2_001.fastq.gz -t 16 -o /projects/site/pred/neurogenomics/users/macnairw/Macnair_2022/output/ms01_alevin_fry/af_zero_mapping/af_map",
    "num_mapped": 0,
    "num_reads": 284823970,
    "percent_mapped": 0.0,
    "runtime_seconds": 235.0
}
```
It's a strange one...! Any ideas what could be going on?

I've shared a folder ("zero_mapping") with you, with the relevant files. Let me know if you need anything else.

Best
Will

**Comment by rob-p** [comment]
Hi @wmacnair,

  Ok, so this seems like another strange one.  I grabbed the first pair of files:

```
zero_mapping_POOL1_S3_L001_R1_001.fastq.gz
zero_mapping_POOL1_S3_L001_R2_001.fastq.gz
```

and tried to map them with `piscem` using the same index from the previous `simpleaf` issue.  In that pair of files, out of `142756504` reads it mapped `126833786`.

The `map_info.json` shows:

```
{
    "cmdline": "sc_ref_mapper -i ../simpleaf_issue_99/piscem_index/index/piscem_idx -g chromium_v3 -1 zero_mapping_POOL1_S3_L001_R1_001.fastq.gz -2 zero_mapping_POOL1_S3_L001_R2_001.fastq.gz -t 16 -o mapping_res",
    "num_mapped": 126833786,
    "num_reads": 142756504,
    "percent_mapped": 88.8462398883066,
    "runtime_seconds": 416.0
}
```

Do you see any obvious differences between our commands, apart from me only using the first pair of files?

--Rob

**Comment by wmacnair** [comment]
Hmm, nothing obvious to me... These are the two `cmdline` entries, with extraneous paths deleted:
```bash
# me:
sc_ref_mapper -i .../piscem_idx -g chromium_v3 \
  -1 zero_mapping_POOL1_S3_L001_R1_001.fastq.gz,zero_mapping_POOL1_S3_L002_R1_001.fastq.gz \
  -2 zero_mapping_POOL1_S3_L001_R2_001.fastq.gz,zero_mapping_POOL1_S3_L002_R2_001.fastq.gz \
  -t 16 -o /af_zero_mapping/af_map

# robp
sc_ref_mapper -i .../piscem_idx -g chromium_v3 \
  -1 zero_mapping_POOL1_S3_L001_R1_001.fastq.gz \
  -2 zero_mapping_POOL1_S3_L001_R2_001.fastq.gz \
  -t 16 -o mapping_res
```
Tagging @marusakod as she has had exactly the same issue, and will be more able to help today and Monday.

Will

**Comment by wmacnair** [comment]
Weird, I've tried running both with both, with just L001, and with just L002 and get 0 reads mapped each time. Calls were:
```
# with all files
/projects/site/pred/neurogenomics/resources/scprocess_data/conda/af/bin/piscem map-sc \
  --index /projects/site/pred/neurogenomics/resources/scprocess_data/data/alevin_fry_home/human_2020-A_splici_clean/index/piscem_idx \
  --threads 16 \
  -o /projects/site/pred/neurogenomics/users/macnairw/tmp/af_zero_mapping/af_map \
  -1 /projects/site/pred/neurogenomics/users/macnairw/_sharing/zero_mapping/zero_mapping_POOL1_S3_L001_R1_001.fastq.gz,/projects/site/pred/neurogenomics/users/macnairw/_sharing/zero_mapping/zero_mapping_POOL1_S3_L002_R1_001.fastq.gz \
  -2 /projects/site/pred/neurogenomics/users/macnairw/_sharing/zero_mapping/zero_mapping_POOL1_S3_L001_R2_001.fastq.gz,/projects/site/pred/neurogenomics/users/macnairw/_sharing/zero_mapping/zero_mapping_POOL1_S3_L002_R2_001.fastq.gz \
  --geometry chromium_v3

# with just L001
/projects/site/pred/neurogenomics/resources/scprocess_data/conda/af/bin/piscem map-sc \
  --index /projects/site/pred/neurogenomics/resources/scprocess_data/data/alevin_fry_home/human_2020-A_splici_clean/index/piscem_idx \
  --threads 16 \
  -o /projects/site/pred/neurogenomics/users/macnairw/tmp/af_zero_mapping/af_map \
  -1 /projects/site/pred/neurogenomics/users/macnairw/_sharing/zero_mapping/zero_mapping_POOL1_S3_L001_R1_001.fastq.gz \
  -2 /projects/site/pred/neurogenomics/users/macnairw/_sharing/zero_mapping/zero_mapping_POOL1_S3_L001_R2_001.fastq.gz \
  --geometry chromium_v3

# with just L002
/projects/site/pred/neurogenomics/resources/scprocess_data/conda/af/bin/piscem map-sc \
  --index /projects/site/pred/neurogenomics/resources/scprocess_data/data/alevin_fry_home/human_2020-A_splici_clean/index/piscem_idx \
  --threads 16 \
  -o /projects/site/pred/neurogenomics/users/macnairw/tmp/af_zero_mapping/af_map \
  -1 /projects/site/pred/neurogenomics/users/macnairw/_sharing/zero_mapping/zero_mapping_POOL1_S3_L002_R1_001.fastq.gz \
  -2 /projects/site/pred/neurogenomics/users/macnairw/_sharing/zero_mapping/zero_mapping_POOL1_S3_L002_R2_001.fastq.gz \
  --geometry chromium_v3
```

It's frustrating not to be able to replicate...

What are your first thoughts on what could be wrong?

Will

**Comment by wmacnair** [comment]
Ah interesting, thanks! Very strange that this one sample in the study is v2 while the others are v3...

It also makes me slightly concerned about whether we have the right chemistry for the other samples in the study. Do you have any suggestions for how to check this?

I guess we would call this user error rather than a bug, but could it be helpful to add a suggestion to the error message? e.g. when 0 reads are mapped, suggest rerunning with an alternative chemistry?

Thanks as ever for the speedy response!
Will

**Comment by rob-p** [comment]
Hi @wmacnair,

  Of course; no worries!  We can certainly add some diagnostics and warnings and will do that for the next release.  It's easier (and safer) from our end than adding full auto-detection.

  The easiest way for you to check is just to look at the reads in the R1 file. The v2 chemisty uses a 16bp barcode and a 10bp UMI, while v3 uses a 16bp barcode and a 12bp UMI. While it's not strictly required that content after the barcode and umi are not sequenced, in most samples this simply implies that a v2 file will have a 26bp read 1 and v3 files will have a 28bp read 1.  This is one quick check for the chemistry.

Best,
Rob

**Comment by wmacnair** [comment]
Hi @rob-p 

It turns out that this issue was a bit stranger than we originally thought...

Apparently this sequencing run included samples from two different kits:
- 10x single cell 5' kit v1.1
- 10x single cell 3' v3
To allow both to be sequenced together, the read lengths were chosen such that both should work. This ended up being 26 nt for R1 (16 nt for 10x barcode, 10 nt for UMI), and 90 nt for R2.

I was thinking that this wouldn't work with `simpleaf`, but then I just discovered this piece of documentation:
[a-note-on-the-chemistry-flag](https://simpleaf.readthedocs.io/en/latest/quant-command.html#a-note-on-the-chemistry-flag) :D

Previously, just hacking around, we got something that seemed to work by using v2 chemistry, but with the v3 barcode whitelist. I'm now thinking that that is exactly the right thing to do, because the chemistry in v2 is "1{b[16]u[10]x:}2{r:}", which is exactly what we need.

I think that's the case, but it would be great if you could confirm!

Best
Will

**Comment by rob-p** [comment]
This is .... a very strange sample. So they mixed a sequencing run with data from 2 separate technologies?

So, among the available options (at least the ones that don't involve trying to split/de-multiplex the reads before quantification), the geometry you suggest seems right. The 5' kit v1.1 has 10bp UMI as you say, so you need to use the shorter geometry specification for it.

Of course, this means that you'll lose the last 2bp of the UMI information from the v3 chemistry.  This is unavoidable, as it wasn't sequenced - so that's not a `simpleaf` problem, but a general one.  

I couldn't immediately find information about the 5' v1.1 kit "whitelist".  Assuming it uses the same barcodes as v3, then this approach seems to make total sense.  I'll be interested to see what you get from the sample, of course ;P.

Best,
Rob

**Comment by wmacnair** [comment]
Yes it is very strange, and it would have saved quite a bit of confusion if they had just split into two runs... 🙄 

@marusakod found [this description](https://kb.10xgenomics.com/hc/en-us/articles/115004506263-What-is-a-barcode-whitelist) of which barcode lists are used in which kits:
![image](https://github.com/COMBINE-lab/piscem/assets/32297936/3a58de93-3879-408e-b6cf-18373c36fc12)

(One minor clarification - we're only looking at the 3' v3 samples, so I don't think we need to be concerned with demultiplexing.)

One comment here - for all that `CellRanger` is muuuuch much slower and handles spliced / unspliced worse etc, it is actually pretty good at guessing what the right chemistry is for a given sample. I think it has guessed right for all of the unusual samples we've seen, including these. More broadly, `CellRanger` handles "unusual" sample configurations well (e.g. multiplexed, multiome with ATACseq), while these take a bit more effort and knowledge with `simpleaf`.

As a user, it would be great if this is some functionality that could be added to `simpleaf` at some point. I'm sure it's on your list, but here's another **+1** in favour 😄.

Best, and thanks again
Will
