### ISSUE TITLE
Error during graph construction

### ISSUE THREAD

**Issue by darcyabjones** [COMBINE-lab/piscem#18]
Hi there,

I'm trying out the new version of simpleaf that allows decoys with piscem mapping.
I'm coming across this error when it's trying to build the cuttlefish graph.

```
********
Error: Cannot open temporary file MY_INDEX_DIR/index/kmc_01021.bin

Usage :
Efficiently construct the compacted de Bruijn graph from sequencing reads or reference sequences
Usage:
  cuttlefish build [OPTION...]

...

directory already exists
fatal runtime error: Rust cannot catch foreign exceptions
====
Error: piscem index failed to build succesfully ExitStatus(unix_wait_status(134))
```

I've tried building the index separately without the decoys with the command.

```
piscem build --ref-seqs MY_INDEX_DIR/ref/roers_ref.fa --klen 31 --mlen 19 --threads 1 --output testing
```

Which yields the same error, but also logs an "Aborted (core dumped)" line at the end.
I've also tried using multiple threads, setting `--work-dir testing` and adding `--keep-intermediate-dbg`.

So i thought it was time to ask the developers :)

Some info:
- Installed via conda
- piscem version 0.7.0
- simpleaf version 0.15.1
- Genome and genes are from TAIR10 (https://www.arabidopsis.org/download/)
- RedHat linux 8.7
- AMD EPYC 7713 64-Core Processors

Thanks for all of your great work!

Cheers,
Darcy

PS. Is it worth waiting for a fix? I'd like to use the selective alignment method as my genomes are relatively small and it seems to be more reliable than sketch mapping. But the logged output and code of `simpleaf index` suggests to me that no decoys are provided to salmon. So i'm a little bit unclear on what the "best" method currently is and whether the Hjörleifsson decoy method is really that different.

**Comment by rob-p** [comment]
Hi @darcyabjones,

  Thanks for the detailed report. You probably need to increase the file handle limit (see e.g. [here](https://github.com/COMBINE-lab/cuttlefish?tab=readme-ov-file#note)). Piscem uses a different de bruijn construction than salmon, which uses less memory but writes more small files to disk.  Please let me know if this resolves the issue for you.

--Rob

**Comment by darcyabjones** [comment]
Ah!
Thanks I missed the note in the piscem README.
Yes this resolved the issue and it's working well.

Might be worth adding to the simpleaf docs and/or giving a more informative error message?

Thanks again :)

**Comment by rob-p** [comment]
Good call; we'll update the simpleaf docs as well!
