### ISSUE TITLE
Re-use preexisting KFF

### ISSUE THREAD

**Issue by JosephLalli** [COMBINE-lab/piscem#19]
Hi there,

As part of a pangenomics-based workflow, I have whole-genome kff files for each sample. (Probably important, this does *not* include kff files for each transcriptome).

Is it possible to reuse these kmer counts with piscem? I'm guessing not, but I want to ask here before writing off the possibility.

Thanks,
Joe

**Comment by rob-p** [comment]
This isn't possible, as `piscem` implements a mapping algorithm that requires it's own index (the `piscem` index, which pairs a contig table with the `sshash` data structure for a k-mer index).  I believe this contains strictly more information than the underlying `kff` file, as, with the `piscem` index it's possible not only to enumerate all k-mers, but also to recall the orientation and position of each k-mer within each input reference.  These capabilities are also used by the mapping algorithm.  So apart from not accepting `kff` files as input, I think there is an "information" deficit between what the `piscem` index provides and what is present in `kff` files.

Best,
Rob
